ARG THE_USER_ID=1001
ARG THE_GROUP_ID=1001
RUN DEBIAN_FRONTEND=noninteractive && \
    /usr/sbin/groupadd -g $THE_GROUP_ID spring && \
    /usr/sbin/useradd -l -u $THE_USER_ID -G spring -g $THE_GROUP_ID spring && \
    mkdir logs && chgrp spring logs && chmod ug+rwx logs

# run as non-root
USER spring:spring

# main REST service and OpenAPI /swagger-ui/index.html
EXPOSE 8080
# actuator metrics /actuator/health, /actuator/prometheus
EXPOSE 8081

CMD ["java","-jar","app.jar"]